color0 #404944
color1 #ffb4ab
color2 #8ad6b6
color3 #b3ccbf
color4 #a6cce0
color5 #8ad6b6
color6 #b3ccbf
color7 #dee4df
color8 #89938d
color9 #ffb4ab
color10 #8ad6b6
color11 #b3ccbf
color12 #a6cce0
color13 #8ad6b6
color14 #b3ccbf
color15 #dee4df

cursor                #dee4df
cursor_text_color     #0f1512
background            #0f1512
foreground            #dee4df
selection_foreground  #bfc9c2
selection_background  #404944
active_border_color   #8ad6b6
inactive_border_color #404944
url_color             #8ad6b6

active_tab_foreground   #003828
active_tab_background   #8ad6b6
inactive_tab_foreground #bfc9c2
inactive_tab_background #404944
cursor_trail_color      #bfc9c2
