$primary_paletteKeyColor = 667c6c
$secondary_paletteKeyColor = 717971
$tertiary_paletteKeyColor = adb9cd
$neutral_paletteKeyColor = 777775
$neutral_variant_paletteKeyColor = 737872
$background = 040504
$onBackground = e3e2e0
$surface = 040504
$surfaceDim = 040504
$surfaceBright = 101010
$surfaceContainerLowest = 030303
$surfaceContainerLow = 070707
$surfaceContainer = 090909
$surfaceContainerHigh = 0c0c0c
$surfaceContainerHighest = 0f0f0f
$onSurface = e3e2e0
$surfaceVariant = 131313
$onSurfaceVariant = c3c8c1
$inverseSurface = e3e2e0
$inverseOnSurface = 30312f
$outline = 8d928c
$outlineVariant = 434843
$shadow = 000000
$scrim = 000000
$surfaceTint = 262826
$primary = 9ab19f
$onPrimary = 112418
$primaryContainer = a7beac
$onPrimaryContainer = 394d3f
$inversePrimary = 4e6354
$secondary = c0c9c0
$onSecondary = 2a322c
$secondaryContainer = 404942
$onSecondaryContainer = afb7af
$tertiary = bbc7dc
$onTertiary = 253141
$tertiaryContainer = 8691a4
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = d1e8d5
$primaryFixedDim = b5ccba
$onPrimaryFixed = 0c1f14
$onPrimaryFixedVariant = 374b3d
$secondaryFixed = dce5db
$secondaryFixedDim = c0c9c0
$onSecondaryFixed = 161d18
$onSecondaryFixedVariant = 404942
$tertiaryFixed = d7e3f8
$tertiaryFixedDim = bbc7dc
$onTertiaryFixed = 101c2b
$onTertiaryFixedVariant = 3c4858
$term0 = 080808
$term1 = 769e00
$term2 = 88df91
$term3 = aff89f
$term4 = 7eb69c
$term5 = c6a844
$term6 = 96d8a9
$term7 = d2dbca
$term8 = 9ea598
$term9 = 85b900
$term10 = 8af499
$term11 = d7ffcc
$term12 = a9c8b3
$term13 = cec06b
$term14 = a2ecb5
$term15 = ffffff
$rosewater = f1f3e5
$flamingo = e3e4c5
$pink = bae2ff
$mauve = 5bd0df
$red = c5b542
$maroon = c6c177
$peach = b5d89e
$yellow = def9d6
$green = a5f1bb
$teal = abeeca
$sky = 9debca
$sapphire = 7cd8ba
$blue = 5fcfb8
$lavender = 87dccc
$klink = 03997d
$klinkSelection = 04997d
$kvisited = 008ca9
$kvisitedSelection = 008ca9
$knegative = 838f00
$knegativeSelection = 838f00
$kneutral = 6bbe38
$kneutralSelection = 6cbe38
$kpositive = 2dc077
$kpositiveSelection = 2dc077
$text = e3e2e0
$subtext1 = c3c8c1
$subtext0 = 8d928c
$overlay2 = 1c1c1c
$overlay1 = 191919
$overlay0 = 161616
$surface2 = 121212
$surface1 = 0d0d0d
$surface0 = 060706
$base = 000100
$mantle = 000100
$crust = 000100
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
