#listener {
#    timeout = 600 # 10mins -> Screen lock
#    on-timeout = loginctl lock-session
#}

#listener {
#    timeout = 1200 # 20mins -> Screen goes off
#    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
#    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
#}

#listener {
#  timeout = 900 # 15mins -> Sleep
#    on-timeout = $suspend_cmd
#}
