-- Generated by nwg-displays on 2026-06-07 at 18:52:38. Do not edit manually.

hl.monitor({
    output = "desc:AOC Q27G4_D 1T0R7HA007040",
    mode = "2560x1440@200.0",
    position = "0x0",
    scale = 1.0,
    bitdepth = 10
})
hl.monitor({
    output = "desc:AOC G2460PG #ASOkEZB9ChHd",
    mode = "1920x1080@143.98",
    position = "2560x150",
    scale = 1.0,
    bitdepth = 10
})
