# hyprlang noerror false
# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method

# Center the Cursor on 1440p Monitor
exec-once = hyprctl dispatch movecursor 3200 720
exec-once = hyprctl dispatch focusmonitor DP-6

exec-once = ~/.config/hypr/custom/scripts/start-spotify.sh
exec-once = ~/.config/hypr/custom/scripts/set-ee-default.sh

# exec-once = waypaper --restore
