# hyprlang noerror false
# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

# My Apps - Special Workspace Rules

# Spotify - Special Workspace Rules
windowrule = workspace special:music silent, match:class Spotify|spotify
windowrule = opacity 0.9, match:class Spotify|spotify

# Discord - Special Workspace Rules
windowrule = workspace special:communication silent, match:initial_class Discord|discord
windowrule = opacity 0.97, match:initial_class Discord|discord

# Slack - Special Workspace Rules
windowrule = workspace special:slack silent, match:class Slack|slack
windowrule = opacity 0.97, match:class Slack|slack

# Btop - Special Workspace Rules
windowrule = workspace special:sysmon, match:class btop
windowrule = opacity 0.8, match:class btop|Btop

# Zed - Opacity
windowrule= opacity 0.97, match:class dev.zed.Zed

# Steam - Floating/Opacity
windowrule = match:initial_title ^(Friends List|friends list)$, float on
windowrule = match:initial_class ^(Steam|steam)$, float on
windowrule = match:initial_title ^(Steam)$, tile on
windowrule = opacity 0.97, match:class Steam|steam

# Kitty - Opacity
windowrule = opacity 0.97, match:class Kitty|kitty

# Waypaper
#windowrule = match:class ^(waypaper)$, float on
#windowrule = match:class ^(waypaper)$, size (monitor_w*.45) (monitor_h*.55)
#windowrule = match:class ^(waypaper)$, move (monitor_w*.275) (monitor_h*.035)
#windowrule = match:class ^(waypaper)$, animation slidevert

# Discord RPC - Floating
windowrule = match:class ^(rpc-toggle)$, float on
windowrule = match:class ^(rpc-toggle)$, center on
windowrule = match:class ^(rpc-toggle)$, size (monitor_w*.45) (monitor_h*.55)

# QRClip - Floating
windowrule = match:class ^(QR-clip)$, float on
windowrule = match:class ^(QR-clip)$, center on
windowrule = match:class ^(QR-clip)$, size (monitor_w*.45) (monitor_h*.55)

# Telegram - No Focus Steal
windowrule = no_focus 1, match:class TelegramDesktop|telegram-desktop
windowrule = no_focus 1, match:title Telegram|telegram

# Superhuman - Opacity
windowrule = opacity 0.97, match:title Superhuman|superhuman
windowrule = opacity 0.97, match:initial_title Superhuman|superhuman

# Dolphin - Opacity
windowrule = opacity 0.97, match:class org.kde.dolphin

# Quo - Opacity
windowrule = opacity 0.97, match:initial_title quo|Quo

# WhatsApp - Opacity
windowrule = opacity 0.98, match:title WhatsApp Web|whatsapp web
