# hyprlang noerror false
# For all available variables, see ~/.config/hypr/hyprland/variables.conf
#
# Sets Mouse Acceleration -> Off // Sensitivity -> Raw
input {
    accel_profile = flat
    sensitivity = 0
}

# Removes Extra Cursor on 2nd Monitor
#cursor {
 #   no_hardware_cursors = true
#}
$browser = brave --profile-directory="Default" --disable-gpu-compositing
$workbrowser = brave --profile-directory="Profile 1" --disable-gpu-compositing
$taskManager = ~/.config/hypr/hyprland/scripts/sysmon.sh