# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#040504

# Main text color
theme[main_fg]=#e3e2e0

# Title color for boxes
theme[title]=#e3e2e0

# Highlight color for keyboard shortcuts
theme[hi_fg]=#9ab19f

# Background color of selected item in processes box
theme[selected_bg]=#090909

# Foreground color of selected item in processes box
theme[selected_fg]=#9ab19f

# Color of inactive/disabled text
theme[inactive_fg]=#8d928c

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#bbc7dc

# Background color of the percentage meters
theme[meter_bg]=#8d928c

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#bbc7dc

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#5bd0df
theme[mem_box]=#a5f1bb
theme[net_box]=#c6c177
theme[proc_box]=#5fcfb8

# Box divider line and small boxes line color
theme[div_line]=#434843

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#a5f1bb
theme[temp_mid]=#def9d6
theme[temp_end]=#c5b542

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#abeeca
theme[cpu_mid]=#7cd8ba
theme[cpu_end]=#87dccc

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#5bd0df
theme[free_mid]=#87dccc
theme[free_end]=#5fcfb8

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#7cd8ba
theme[cached_mid]=#5fcfb8
theme[cached_end]=#87dccc

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#b5d89e
theme[available_mid]=#c6c177
theme[available_end]=#c5b542

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#a5f1bb
theme[used_mid]=#abeeca
theme[used_end]=#9debca

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#b5d89e
theme[download_mid]=#c6c177
theme[download_end]=#c5b542

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#a5f1bb
theme[upload_mid]=#abeeca
theme[upload_end]=#9debca

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#7cd8ba
theme[process_mid]=#87dccc
theme[process_end]=#5bd0df
